<?php
$data = [
    ["id" => 1, "name" =>"Laravel", "category" => "PHP" ],
    ["id" => 2, "name" =>"Symfony", "category" => "PHP" ],
    ["id" => 3, "name" =>"CakePHP", "category" => "PHP" ],
    ["id" => 4, "name" =>"zend framework", "category" => "PHP" ],
    ["id" => 5, "name" =>"codeigniter", "category" => "PHP" ],
    ["id" => 6, "name" =>"Phalcon", "category" => "PHP" ],
    ["id" => 7, "name" =>"FuelPHP", "category" => "PHP" ],
    ["id" => 8, "name" =>"Yii", "category" => "PHP" ],
    ["id" => 9, "name" =>"Slim", "category" => "PHP" ],
    ["id" => 10, "name" =>"Silex", "category" => "PHP" ],
    ["id" => 11, "name" =>"Flight", "category" => "PHP" ],
    ["id" => 12, "name" =>"BEAR.Sunday", "category" => "PHP" ],
    ["id" => 13, "name" =>"Ethna", "category" => "PHP" ],
    ["id" => 14, "name" =>"React", "category" => "Javascript" ],
    ["id" => 15, "name" =>"AngularJS", "category" => "Javascript" ],
    ["id" => 16, "name" =>"Vue.js", "category" => "Javascript" ],
    ["id" => 17, "name" =>"Backbone.js", "category" => "Javascript" ],
    ["id" => 18, "name" =>"jQuery", "category" => "Javascript" ],
    ["id" => 19, "name" =>"Knockout.js", "category" => "Javascript" ],
    ["id" => 20, "name" =>"Django", "category" => "Python" ],
    ["id" => 21, "name" =>"Bottle", "category" => "Python" ],
    ["id" => 22, "name" =>"Flask", "category" => "Python" ],
    ["id" => 23, "name" =>"Tornado", "category" => "Python" ],
];

